name: Test release

on:
  push:
    tags:
      - "v1.*.*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run tests
        run: |
          npm install
          npm run build
          npm run lint
          npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 🔒 Acquire Lock (and auto-release on completion)
        uses: releasetools/mutex@c43feb89589aa9acd7b35652ab0338fe04b17126 # v1
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: "lock"
          id: "verify-release-v0"
          reason: "Verify released v1 version"

      - name: ⏳ Mock action - wait 5 seconds and then continue
        run: sleep 5
